In [17]:
!pip install numpy

In [18]:
import numpy as np

In [19]:
num_array = np.array([1, 2, 3])
num_array

array([1, 2, 3])

# Step 1: Mutable

In [21]:
np.append(num_array, [6,5])

array([1, 2, 3, 6, 5])

In [22]:
np.delete(num_array, [2])

array([1, 2])

In [23]:
## Step 3: Can be indexed

In [24]:
num_array[2]

3

In [25]:
## Step operation

In [26]:
num_array[1:3]

array([2, 3])

# Difference
## Numpy ma multiple garna sakxa array ma sakdaina

In [28]:
num_array = np.array([1, 2, 3.5])
num_array

array([1. , 2. , 3.5])

In [29]:
num_array / 2

array([0.5 , 1.  , 1.75])

In [32]:
num_array = np.array([[1, 2, 3.5], [5, 6, 7]])
num_array

array([[1. , 2. , 3.5],
       [5. , 6. , 7. ]])

In [33]:
np.ndim(num_array)

2

In [ ]:
! pip install numpy
import import as np