In [73]:
# !pip install numpy

In [74]:
import numpy as np

In [75]:
# 1D Dimensional Array

In [76]:
num_array = np.array([1, 2, 3])

In [77]:
np.ndim(num_array)

1

In [78]:
np.shape(num_array)

(3,)

In [79]:
## Two dimensional Array

In [80]:
two_d = np.array([[1,2,3], [4,5,6]])

In [81]:
np.ndim(two_d)

2

In [82]:
np.shape(two_d)

(2, 3)

In [83]:
## Three dimensional Arrat

In [84]:
three_d = np.array([[[2,3],[4,6]],[[2,3],[4,6]]])

In [85]:
np.ndim(three_d)

3

In [86]:
np.shape(three_d)

(2, 2, 2)

# Array multiplication

In [87]:
arr_01 = np.array([ [1,2], [3,4] ])
arr_02 = np.array([ [5,6], [7,8] ])

In [88]:
mat_mul = np.dot(arr_01, arr_02)
mat_mul

array([[19, 22],
       [43, 50]])

In [89]:
arr_01 @ arr_02  ##dot function

array([[19, 22],
       [43, 50]])

In [90]:
arr_01 *arr_02 ## multiplication

array([[ 5, 12],
       [21, 32]])

In [91]:
## Addition ans Substraction

In [96]:
arr_03 = np.array([[1,2],[3,4]])
arr_04 = np.array([[5,6],[7,8]])

In [97]:
add_ele = np.add(arr_03, arr_04)
add_ele

array([[ 6,  8],
       [10, 12]])

In [98]:
ele = np.sum(arr_03)
ele

10

In [99]:
subs = np.subtract(arr_03, arr_04)
subs

array([[-4, -4],
       [-4, -4]])

In [100]:
div = np.divide(arr_03, arr_04)
div ## float ma ans aauxa

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [101]:
mat_div = np.divide(arr_03, 2)
mat_div ## Float ma ans aauxa

array([[0.5, 1. ],
       [1.5, 2. ]])

In [102]:
mat_div = np.divide(arr_03, 2).astype('int')
mat_div # int ma aauni

array([[0, 1],
       [1, 2]])

# Broadcasting

In [105]:
arr_08 = np.array([[1,2],[3,4]])

In [106]:
arr_08.shape

(2, 2)

In [108]:
arr_08 + 3

array([[4, 5],
       [6, 7]])

In [109]:
arr_09 = np.array([[1,2,3],[4,5,6]])

In [111]:
arr_09 + np.array([10,11,12])

array([[11, 13, 15],
       [14, 16, 18]])

In [112]:
num_array = np.array([1,2,3])
num_array

array([1, 2, 3])